namespace patel8sd_Profile // Unified namespace
{
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent(); // Generated by XAML compiler, do NOT manually implement

            MainPage = new AppShell(); // Sets the initial page of the application
        }
    }
}