namespace patel8sd_Profile // Unified namespace
{
    public partial class AppShell : Shell
    {
        public AppShell()
        {
            InitializeComponent(); // Generated by XAML compiler, do NOT manually implement

            // Register the "profile" route so ProfilePage can be navigated to
            Routing.RegisterRoute("profile", typeof(ProfilePage));
        }
    }
}