namespace patel8sd_Profile // Unified namespace
{
    public partial class MainPage : ContentPage
    {
        // These UI elements are automatically connected to the x:Name attributes in MainPage.xaml
        // You do NOT need to declare private fields for them here, nor use FindByName.

        public MainPage()
        {
            InitializeComponent(); // Generated by XAML compiler, do NOT manually implement
        }

        private async void OnSignUpClicked(object sender, EventArgs e)
        {
            // Accessing the Entry and Label controls directly by their x:Name
            string username = usernameEntry.Text?.Trim();
            string email = emailEntry.Text?.Trim();
            string password = passwordEntry.Text;
            string confirmPassword = confirmPasswordEntry.Text;

            if (string.IsNullOrWhiteSpace(username) ||
                string.IsNullOrWhiteSpace(email) ||
                string.IsNullOrWhiteSpace(password) ||
                string.IsNullOrWhiteSpace(confirmPassword))
            {
                errorLabel.Text = "Please fill in all fields.";
                errorLabel.IsVisible = true;
                return;
            }

            if (password != confirmPassword)
            {
                errorLabel.Text = "Passwords do not match.";
                errorLabel.IsVisible = true;
                return;
            }

            errorLabel.IsVisible = false; // Hide error if validation passes


            var uri = $"profile?username={Uri.EscapeDataString(username)}&email={Uri.EscapeDataString(email)}";
            await Shell.Current.GoToAsync(uri);
        }
    }
}