using System.Web; // Needed for HttpUtility.UrlDecode if not using Uri.UnescapeDataString

namespace patel8sd_Profile // Unified namespace
{
    // QueryProperty attributes automatically populate the Username and Email properties
    [QueryProperty(nameof(Username), "username")]
    [QueryProperty(nameof(Email), "email")]
    public partial class ProfilePage : ContentPage
    {
        private string username;
        private string email;

        // The UsernameLabel and EmailLabel fields are automatically created because of x:Name in ProfilePage.xaml
        // No need for FindByName properties or manual field declarations here.

        public string Username
        {
            get => username;
            set
            {
                // Decode the URI-escaped string
                username = Uri.UnescapeDataString(value ?? string.Empty);
                // Update the UI Label if it's already initialized (after InitializeComponent)
                if (UsernameLabel != null)
                {
                    UsernameLabel.Text = $"Username: {username}";
                }
            }
        }

        public string Email
        {
            get => email;
            set
            {
                // Decode the URI-escaped string
                email = Uri.UnescapeDataString(value ?? string.Empty);
                // Update the UI Label if it's already initialized
                if (EmailLabel != null)
                {
                    EmailLabel.Text = $"Email: {email}";
                }
            }
        }

        public ProfilePage()
        {
            InitializeComponent(); // Generated by XAML compiler, do NOT manually implement
            // The QueryProperty setters (Username and Email) will be called *after* this constructor
            // and after InitializeComponent() has connected the x:Name fields.
        }

        // OnAppearing is a good place to ensure UI is updated after navigation and property setting
        protected override void OnAppearing()
        {
            base.OnAppearing();
            // Ensure labels reflect the latest data, especially after the page appears and QueryProperties are set.
            if (UsernameLabel != null)
            {
                UsernameLabel.Text = $"Username: {username}";
            }
            if (EmailLabel != null)
            {
                EmailLabel.Text = $"Email: {email}";
            }
        }

        private async void OnSignOutClicked(object sender, EventArgs e)
        {
            // Navigate back to the previous page (which should be MainPage/Signup)
            await Shell.Current.GoToAsync("..");
        }
    }
}